### ISSUE TITLE
微信测试号Token问题

### ISSUE THREAD

**Issue by SStarbuckS** [ZacharyJia/serverchan#19]
企业微信通知一切正常，想问问这个微信Token(测试号)到底咋弄勒
直接填写随意值到`.env`Token，微信扫码绑定只刷新出二维码，没有其它选项，但测试post链接时首页历史消息是有`wechat`信息的
百度不到只好提个issues问下这个Token到底咱弄勒....
[https://ftp.bmp.ovh/imgs/2020/11/511dd56d5558db43.png
](url)
日志Token是获取正常的：
```shell
[2020-11-03 05:37:55] NULL.INFO: >>>>>>>>
POST /cgi-bin/qrcode/create?access_token=38_JjiCwRpBdMX0HWUHCWzO9AcZ36XkT2-EBT3niJhbSTJsVA3bDstrWEX0EAbvjWdLYtt41cbGeeqlREUC8vEnCi_xrB0Sg68bqbuk7M1Euj1wr4-FBvuVD0Q8zFcxFyAuPpjauImtCTwALHqVOVWdAFAVCD HTTP/1.1
Host: api.weixin.qq.com
Content-Length: 86
User-Agent: GuzzleHttp/6.5.5 curl/7.64.0 PHP/7.1.32
Content-Type: application/json

{"action_name":"QR_SCENE","action_info":{"scene":{"scene_id":1}},"expire_seconds":600}
<<<<<<<<
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/json; encoding=utf-8
Date: Mon, 02 Nov 2020 21:37:55 GMT
Content-Length: 188

{"ticket":"gQET8DwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAyVktlMjA3Z0NkY0QxQ2Itd2h2MTEAAgQzfKBfAwRYAgAA","expire_seconds":600,"url":"http:\/\/weixin.qq.com\/q\/02VKe207gCdcD1Cb-whv11"}
--------
NULL  
```

**Comment by ZacharyJia** [comment]
env里面的token不能随便填，按照下面的指引填写
```
在.env文件中填写好公众号的WECHAT_OFFICIAL_ACCOUNT_APPID、WECHAT_OFFICIAL_ACCOUNT_SECRET和WECHAT_OFFICIAL_ACCOUNT_TOKEN。
```
具体的这些值，去测试号的后台网页上能看到。

此外还需要按指引创建消息模板，然后填template_id

绑定的时候只有二维码是正常的，扫码绑定即可。

**Comment by SStarbuckS** [comment]
纳闷的是测试号后台接口配置URL填写程序访问域名
Token填写与.env中WECHAT_OFFICIAL_ACCOUNT_TOKEN一样的值
测试号接口配置提交失败
[https://ftp.bmp.ovh/imgs/2020/11/6f04e56e1f02a7e9.png](url)
[https://ftp.bmp.ovh/imgs/2020/11/b9e317eb39869e1e.png](url)

**Comment by ZacharyJia** [comment]
> 纳闷的是测试号后台接口配置URL填写程序访问域名
> Token填写与.env中WECHAT_OFFICIAL_ACCOUNT_TOKEN一样的值
> 测试号接口配置提交失败
> [https://ftp.bmp.ovh/imgs/2020/11/6f04e56e1f02a7e9.png](url)
> [https://ftp.bmp.ovh/imgs/2020/11/b9e317eb39869e1e.png](url)

配置的时候，微信会去验证一下，所以必须能验证通过才会配置成功。
填url的时候不要直接填域名，填成 `http://example.com/wechat`，后面那个`/wechat`是这个项目配置给微信使用的接口。

**Comment by SStarbuckS** [comment]
THX,配置成功了
