### ISSUE TITLE
企业微信ID验证失败

### ISSUE THREAD

**Issue by tt508618** [ZacharyJia/serverchan#2]
请问绑定绑定企业微信出现企业微信ID验证失败这要怎么解决啊？

**Comment by ZacharyJia** [comment]
请提供具体的配置项和报错提示

**Comment by tt508618** [comment]
这是报错信息
<<<<<<<<
HTTP/1.1 200 OK
Connection: keep-alive
Error-Code: 60111
Error-Msg: userid not found, hint: [1559277777_1_62f42bff15e4e3fb851fc11f853c1113], more info at https://open.work.weixin.qq.com/devtool/query?e=60111
Content-Type: application/json; charset=UTF-8
Content-Length: 218

{"errcode":60111,"errmsg":"userid not found, hint: [1559277777_1_62f42bff15e4e3fb851fc11f853c1113], more info at https://open.work.weixin.qq.com/devtool/query?e=60111","department":[],"order":[],"is_leader_in_dept":[]}
--------
NULL  @ZacharyJia

**Comment by tt508618** [comment]
![QQ截图20190531130400](https://user-images.githubusercontent.com/30516411/58682970-372c3f80-83a5-11e9-8fe5-84d8b8444f99.png)

**Comment by ZacharyJia** [comment]
这个错误是userid不存在，你检查一下你输入的企业微信的用户ID是否正确。用户ID可以在这个界面看到
<img width="1275" alt="屏幕快照 2019-05-31 下午1 17 20" src="https://user-images.githubusercontent.com/7402471/58683457-0fd67200-83a7-11e9-92e8-461e0369ffaf.png">

**Comment by tt508618** [comment]
感谢指导终于解决了~~~

**Comment by tt508618** [comment]
请问大佬是不是不支持Markdown 语法啊

**Comment by ZacharyJia** [comment]
对，目前没有提供这个的支持
不过其实挺简单，也不需要编辑器，加个简单的渲染器就可以了

**Comment by tt508618** [comment]
我这小白不知道怎么加！！没有Markdown现在推送到微信上消息很乱~~~

**Comment by tt508618** [comment]
大佬有没有打算要更新支持一下吗？
