### ISSUE TITLE
是不是不支持Markdown 语法啊

### ISSUE THREAD

**Issue by ZacharyJia** [ZacharyJia/serverchan#4]
是不是不支持Markdown 语法啊

_Originally posted by @tt508618 in https://github.com/ZacharyJia/serverchan/issues/2#issuecomment-498010394_

**Comment by ZacharyJia** [comment]
@tt508618
[v0.1 ](https://github.com/ZacharyJia/serverchan/releases/tag/v0.1) 已经提供content字段的Markdown支持。
需要在.env 文件中配置`ENABLE_MARKDOWN`为`true`

**Comment by tt508618** [comment]
还有一个小问题就是不能识别表格！这有办法解决吗？
![J)(}R`N)KR@_BN9ECW_FYMM](https://user-images.githubusercontent.com/30516411/58762274-0dc80b00-8581-11e9-908d-ca6df2988327.png)

server酱的是这样的
![R2X0T}SN8}8)81{AK%C250D](https://user-images.githubusercontent.com/30516411/58762278-11f42880-8581-11e9-8b10-199d9f5e7e92.png)

**Comment by ZacharyJia** [comment]
可以用嵌入html代码的方式实现
如果要使用Markdown实现的话，可能要参考Markdown解析器的文档
https://github.com/GrahamCampbell/Laravel-Markdown 目前使用的是这个，它是 CommonMark 的laravel wrapper，可以参考文档自己配置

**Comment by tt508618** [comment]
谢啦~研究一下午终于搞定了。

**Comment by tt508618** [comment]
@ZacharyJia 请问这里的卡片页面是否也可以支持Markdown？
![)0V0 B 0T_RTBG GDXN9R%B](https://user-images.githubusercontent.com/30516411/67666915-bb600e80-f9a7-11e9-984b-5327f1c2252c.png)
